// Quality gate for knowledge extracted from uploaded documents.
//
// Runs BEFORE rules are committed to the knowledge base. Catches the two failure
// modes that historically polluted the KB:
//   1. Hallucinated specifics — a rule asserts a number/price/phone/address that
//      does NOT appear in its own source quote (the model invented it).
//   2. Junk content — placeholders, empty/degenerate bodies, marketing filler.
//
// Non-blocking by design: returns warnings the caller surfaces to the admin and
// logs. The admin still decides; we never silently drop their content. The point
// is VISIBILITY at ingest time, so bad extractions are caught at the source
// instead of surfacing as wrong answers weeks later.

export interface LintInput {
  ruleCode: string;
  title: string;
  body: string;
  /** The verbatim source text the rule was extracted from. */
  sourceQuote: string;
}

export interface LintWarning {
  ruleCode: string;
  kind: 'hallucinated_fact' | 'placeholder' | 'too_short' | 'too_long' | 'filler' | 'polarity_conflict';
  detail: string;
}

const PLACEHOLDER = /\b(lorem ipsum|todo|tbd|placeholder|xxxx+|\.\.\.\.\.+|пример текста|заполнить)\b/i;

// Generic marketing/atmospheric filler that has no place in an operational rule.
// Russian tails use [а-яё]*, NOT \w* — JS \w is ASCII-only, so "волшебная" /
// "восхитительное" / "уютной атмосфере" would slip past a \w pattern.
const FILLER = /(незабываем|атмосфер[ауеоы]|погрузитесь|уютн[а-яё]*\s+атмосфер|тёплая\s+атмосфер|волшебн[а-яё]*|восхитительн[а-яё]*)/i;

const MIN_BODY = 12;     // chars — shorter than this carries no operational content
const MAX_BODY = 4000;   // chars — a single rule this long is really many rules

// JS \b = ASCII \w only. In Russian `/\bтребуется\b/` never matches.
const CYR_BEFORE = '(?<![а-яёa-z])';
const CYR_AFTER = '(?![а-яёa-z])';

/** Extract "hard" facts (numbers, prices, phones) that must be traceable to the source.
 *
 * Implementation note: we run the regex directly on the raw text using `\b` word boundaries.
 * The old approach of `text.replace(/\s+/g, '')` was incorrect: it concatenated adjacent
 * numbers ("630 1540" → "6301540"), so every individual price appeared "hallucinated"
 * because the merged string never matched the extracted body number.
 *
 * Trade-off: Russian thousand-separator spaces ("1 540" meaning 1540) are NOT collapsed.
 * This means "1 540" extracts "540" (≥3 digits) but not "1540". In practice, our source
 * quotes are generated by the LLM which writes full unspaced numbers, so this is fine.
 */
function hardFacts(text: string): string[] {
  const facts: string[] = [];
  // Standalone numbers of 3+ digits, bounded by non-digit chars on both sides
  for (const m of text.matchAll(/\b\d{3,}\b/g)) facts.push(m[0]);
  return [...new Set(facts)];
}

/**
 * Имена улиц/площадей из тела. Числовая проверка выше берёт только 3+ цифры,
 * поэтому «Исаакиевская площадь 11» против цитаты «ул. Оптиков, 35к1» молчала:
 * 11 и 35 — по две цифры, а текст адреса не сравнивался вовсе.
 */
function addressNames(text: string): string[] {
  const names = new Set<string>();
  const patterns = [
    new RegExp(
      `${CYR_BEFORE}(?:ул\\.?|улица|пр\\.?-?кт\\.?|проспект|пер\\.?|переулок|наб\\.?|набережная|ш\\.?|шоссе|бул\\.?|бульвар)\\s+([а-яё-]{4,})${CYR_AFTER}`,
      'giu'
    ),
    new RegExp(`${CYR_BEFORE}([а-яё-]{4,})\\s+площад`, 'giu'),
  ];
  for (const re of patterns) {
    for (const match of text.matchAll(re)) {
      names.add(match[1].toLowerCase().replace(/ё/g, 'е'));
    }
  }
  return [...names];
}

type StemPolarity = 'pos' | 'neg' | 'mixed' | 'absent';

const POLARITY_STEMS: Array<{ id: string; stem: string }> = [
  { id: 'требуется', stem: 'требуется' },
  { id: 'нуж', stem: 'нуж(?:ен|на|но|ны)' },
  { id: 'можно', stem: 'можно' },
  { id: 'входит', stem: 'входит' },
];

function polarityOf(text: string, stem: string): StemPolarity {
  const re = new RegExp(`${CYR_BEFORE}((?:не)\\s+)?${stem}${CYR_AFTER}`, 'giu');
  let pos = 0;
  let neg = 0;
  for (const match of text.matchAll(re)) {
    if (match[1]) neg += 1;
    else pos += 1;
  }
  if (pos > 0 && neg > 0) return 'mixed';
  if (pos > 0) return 'pos';
  if (neg > 0) return 'neg';
  return 'absent';
}

function oppositePolarity(a: StemPolarity, b: StemPolarity): boolean {
  return (a === 'pos' && b === 'neg') || (a === 'neg' && b === 'pos');
}

/**
 * Lint one extracted rule against its source. Returns 0+ warnings.
 * The anti-hallucination check compares digit-runs (>=3 digits) in the rule body
 * to those in the source quote: a 3+ digit number in the body that is absent from
 * the source is very likely invented (e.g. a price or phone the model guessed).
 */
export function lintRule(input: LintInput): LintWarning[] {
  const warnings: LintWarning[] = [];
  const body = (input.body ?? '').trim();
  const title = (input.title ?? '').trim();
  const quote = input.sourceQuote ?? '';
  const code = input.ruleCode;

  if (body.length < MIN_BODY) {
    warnings.push({ ruleCode: code, kind: 'too_short', detail: `body is ${body.length} chars` });
  }
  if (body.length > MAX_BODY) {
    warnings.push({ ruleCode: code, kind: 'too_long', detail: `body is ${body.length} chars — likely several rules` });
  }
  if (PLACEHOLDER.test(body)) {
    warnings.push({ ruleCode: code, kind: 'placeholder', detail: 'contains placeholder text' });
  }
  if (FILLER.test(body)) {
    warnings.push({ ruleCode: code, kind: 'filler', detail: 'contains marketing/atmospheric filler' });
  }

  const sourceFacts = new Set(hardFacts(quote));
  for (const fact of hardFacts(body)) {
    if (!sourceFacts.has(fact)) {
      warnings.push({
        ruleCode: code,
        kind: 'hallucinated_fact',
        detail: `number "${fact}" is in the rule but not in its source quote`,
      });
    }
  }

  const quoteNorm = quote.toLowerCase().replace(/ё/g, 'е');
  for (const name of addressNames(body)) {
    if (!quoteNorm.includes(name)) {
      warnings.push({
        ruleCode: code,
        kind: 'hallucinated_fact',
        detail: `address "${name}" is in the rule but not in its source quote`,
      });
    }
  }

  // Полярность по ОДНОМУ стему. Смешанное предложение («паспорт требуется,
  // запись не требуется») не помечаем: иначе ловим любое «не» в том же абзаце.
  // Покрытие узкое — цитата и тело делят предикат редко, — но инверсия
  // «требуется» / «не требуется» в одном правиле это уже готовое враньё.
  for (const { id, stem } of POLARITY_STEMS) {
    const bodyPol = polarityOf(body, stem);
    if (bodyPol === 'absent' || bodyPol === 'mixed') continue;
    const quotePol = polarityOf(quote, stem);
    const titlePol = polarityOf(title, stem);
    if (oppositePolarity(bodyPol, quotePol) || oppositePolarity(bodyPol, titlePol)) {
      warnings.push({
        ruleCode: code,
        kind: 'polarity_conflict',
        detail: `body asserts ${bodyPol} «${id}», but title/quote assert the opposite`,
      });
    }
  }

  return warnings;
}

/** Lint a batch; returns a flat list of warnings across all rules. */
export function lintRules(inputs: LintInput[]): LintWarning[] {
  return inputs.flatMap(lintRule);
}
